#!/data/data/com.termux/files/usr/bin/bash

# Coloring
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'
PINK='\033[0;35m'

# Banner
clear


echo -e "${YELLOW}-----------------------------------${NOCOLOR}"
echo -e "${RED}欢迎使用BT 自动制作美化工具${NOCOLOR}"
echo -e "${RED}卡密验证时显示网络错误 请更换网络或者切换系统${NOCOLOR}"
echo -e "${YELLOW}-----------------------------------${NOCOLOR}"


function xt1 {
     "./xynbxm/rc1"
     echo -e "\033[1;33m程序运行结束.输入\033[0;31m 4 \033[1;33m既可退出 BT\033[0m"
    echo -e "1)常用系统" 
    echo -e "2)备用系统"
    echo -e "3)系统版本" 
    echo -e "4)退出BT"
}

function xt2 {
     "./xynbxm/rc6"
      echo -e "\033[1;33m程序运行结束.输入\033[0;31m 4 \033[1;33m既可退出 BT\033[0m"
    echo -e "1)常用系统" 
    echo -e "2)备用系统"
    echo -e "3)系统版本" 
    echo -e "4)退出BT"
}

function xtbb() {
clear
local url=https://xiaoy666.icu/bt/xtbb.txt
echo -e "          ${LIGHTPURPLE}by 小烊 ${NOCOLOR}"
echo -e "${YELLOW}-----------------------------------${NOCOLOR}"
echo -e "自动制作工具: ${LIGHTGREEN}BT${NOCOLOR}"
echo -e "${YELLOW}-----------------------------------${NOCOLOR}"
echo " "
    local content=$(curl -s "$url")
    local text=$(echo "$content" | grep -oP '(?<=<p>).*?(?=</p>)')
    echo -e "\033[1;34m$content\033[0m"
    echo " "
    echo -e "${LIGHTPURPLE}开发者:小烊 @XYNBXM${NOCOLOR}"
    echo -e "\033[32m当前系统版本为 \033[0;31mBTv4 \033[1;33m请核对是否与上述最新版本一致\033[0m"
    echo -e "1)常用系统" 
    echo -e "2)备用系统"
    echo -e "3)系统版本" 
    echo -e "4)退出BT"
}

PS3="请选择系统:"
options=("常用系统" "备用系统" "系统版本" "退出BT")


select opt in "${options[@]}"
do
 case $opt in
    
     "常用系统")
      xt1
    ;;
    "备用系统")
     xt2
    ;;
    "系统版本")
     xtbb
    ;;
   "退出BT")
    exit
    ;;
     *) echo "invalid option $REPLY";;
  esac
done


